### ISSUE TITLE
Furnace Minecarts Are Not Affected

### ISSUE THREAD

**Issue by abitcher** [audaki/minecraft-cart-engine#29]
Furnace minecarts seem to be significantly slower than regular minecarts, but seem to instantly accelerate any minecart they bumped into? Fabric 1.20.1 latest.
Here's a clip: https://medal.tv/games/minecraft/clips/2amNMYfRHavACz/d1337kmCQ8ZT?invite=cr-MSx3d0csMTk4NzQ5NDE5LA

**Comment by abitcher** [comment]
> @abitcher That is correct, furnace minecarts are not changed by this mod at all by design

Why? I see that unrideable minecarts are not affected to avoid breaking farms, but furnace minecarts are not used like that. A furnace minecart's sole purpose is to provide speed to minecarts in front of it, and using furnace minecarts like in a locomotive could be a fun way to get carts even faster and add some resource management play.

**Comment by audaki** [comment]
@abitcher I’ll reopen for now, we can discuss this, maybe you can change my mind.

Even for a normal cart the speed is only increased when a rider is in there (this also helps you so you can catch a free-riding cart if you space your boost rails far enough).

So when an empty cart is used in a redstone contraption, it will keep its vanilla speed. 

A furnace cart doesn’t even have a link to other carts! People use a model collision bug to stick a cart into a furnace cart, but this is not a real feature of vanilla minecart (and often enough causes bugs). So the only proper way for a furnace minecart to be used would be if it pushes your cart (being pulled is a bug!).

The furnace cart then again doesn’t have any info if it’s used in a redstone contraption or to push a player, since the furnace cart doesn’t have any info about riders. There’s no way to differentiate it in an acceptable manner.

So *all* furnace carts would have to receive the increased speed.

About the pulling being a collision bug, you can see this for example here: https://youtu.be/RSiuwCx36WE?si=xmggkHedpZGIcxP4&t=345

If I increased the speed of a furnace cart, instantly the pulling thing (some call it "shunting") would instantly break for all players.

So yeah, just the fact that it would break shunting is imo reason enough to not implement this.

**Comment by audaki** [comment]
@abitcher You originally wanted it for Linkart, and I guess it makes more sense in combination with Linkart

**Comment by abitcher** [comment]
Shunting is a very small use though. And it could be a configuration option for those who do use it. Pushing, pulling, whichever doesn't matter, I just want my train rides to be boosted somehow with furnace minecarts. If they are unable to push minecarts in vanilla for some reason, this could be fixed with this mod? (and disabled with the same configuration option)

Since a furnace minecart doesn't have any uses beyond increasing the speed of other minecarts, I think they should be buffed to be able to fulfil that purpose again. That's my stance.

**Comment by audaki** [comment]
@abitcher Heya, I researched a bit, there’s people who use Furnace Carts for creative purposes also in redstone. So I’d need to make it configurable and that would make the mod much more complex than it is now.

So I respectfully decline and if you’d like to feel free to fork this mod and make the modification yourself. You may even republish the mod then with a new name (with a CC attribution).
