### ISSUE TITLE
config for player-only changes

### ISSUE THREAD

**Issue by ioan-gwenter** [audaki/minecraft-cart-engine#37]
Hi!

Just for some background:
I run a fabric server and some of my players are requesting that we upgrade to 1.21.1 for the faster minecart speeds to build cool railways, however we also have a community of technical players too, and I am aware that the change will break farms like cart-based witch farms

I stumbled along your mod and it seems really promising as it only affects rideable minecarts, and not any mob-based minecarts.

However, there are still alot of technical farms that implement mob-ridden minecarts (like an iron or witch farm) which would still break!

Would it be possible to have a config or option to only allow the mods changes to be applied to only player-boarded minecarts to preserve farm functionality if a user wanted to?

**Comment by audaki** [comment]
I now depend on Fabric API anyway, I could implement this with further game rules.

But before I test this please test it first, v4.0.0 activates the cart experiment for all carts but sets the speed for non rideable carts to 8 blocks/s

Since the behavior is still different technical players may not want to use this mod anyway. And changing the minecart behavior depending on what’s in it would mean a giant rewrite of a lot of code places. So it’s easier to just set speed.

Please test it, and I could add game rules to make everything but player-ridden carts be 8 m/s

**Comment by audaki** [comment]
@ioan-gwenter 

I now depend on Fabric API anyway, I could implement this with further game rules.

But before I test this please test it first, v4.0.0 activates the cart experiment for all carts but sets the speed for non rideable carts to 8 blocks/s

Since the behavior is still different technical players may not want to use this mod anyway. And changing the minecart behavior depending on what’s in it would mean a giant rewrite of a lot of code places. So it’s easier to just set speed.

Please test it, and I could add game rules to make everything but player-ridden carts be 8 m/s

**Comment by audaki** [comment]
@ioan-gwenter 

It is now implemented, see 4.1.0
